#ifndef _____________SEABALL_SHARED_TYPE_DEFS_COMPAT_SUPPORTED_H
#define _____________SEABALL_SHARED_TYPE_DEFS_COMPAT_SUPPORTED_H

#include "_____________seaball_comparison_defs.h"
#include "_____________seaball_int_defs.h"
#include "_____________seaball_ref_defs.h"

#endif